### PR TITLE
Display Entire Geojson When Using L.CanvasFeatureFactory

### PR DESCRIPTION
**Pull request by dnseminara**
Currently, when using `canvasLayer.addCanvasFeatures(L.CanvasFeatureFactory(geojsonData));`, the entire geojson fails to render (sample geojson grabbed from [geojson.xyz](http://geojson.xyz/)).

Within addFeature.js, `features.length` on line 6 looks like it needs to be changed to `features.canvasFeatures.length` - referenced in 94a3c0b.

Also, if a geojson featureCollection fails to have IDs attached to each feature, the click event to fails to identify associated properties. To rectify that, a quick and dirty change is referenced here -     faef1c3

### CODE REVIEW

**Comment by jrmerz** [comment]
@dnseminara thanks!  I'm traveling right now and I want to give this a quick look before I merge.

Just FYI, this is very much a prototype layer.  So all fixes/input welcome.

**Comment by dnseminara** [comment]
@jrmerz, no worries - take your time. Added another commit today - to fix an issue with redraw when an initial pan happens first - prior to zooming in/out.

Thanks for the library!

**Comment by jrmerz** [comment]
The tests folder is from a old project I was working on, let add a complete example with data from  geojson.xyz.

This code has some issues with ids (a relation I would like to remove, but currently required...).  Also, on large dataset I have,  projection breaks if you pan while rendering, will need to debug why.

**Comment by dnseminara** [comment]
I've updated /test with an example from geojson.xyz. 

I'll scrounge around for an example with IDs to see what went amiss - as mentioned, I sort've did a quick and dirty example that would suffice for my no-ID data.

How large is your large dataset? I've tried files up to 20MB and it seemed to work. However, I did notice inefficiencies with data that had 8,000 points within a small confined area using your core lib and not my fork. I ended up using a different plugin for line-string/point data.

**Comment by jrmerz** [comment]
Ok, finally back.  I just created a dev branch.  You mind sending the pull request to dev?  Then I can work out the id issues before merging to master.

I just committed some changes I made that were required for having more than one layer active at a time.  Looks like those changes might cause a conflict, but I can handle on my end.

**Comment by dnseminara** [comment]
Sure. I've also added other little fixes that may/may not be of use to you as well. And since I was committing to the fork - it ended up getting continuously bundled within this pull request.

**Pull request merged**
